### ISSUE TITLE
정말 감사합니다. 

### ISSUE THREAD

**Issue by kksworks** [JeongUkJae/pytistory#4]
이슈로 글을 작성하는게 맞는지는 모르겠지만.. 
원하던 기능이 모두 구현되어있어서, 생각햇던 기능들 쉽게 구현할수있겠네요.

정말감사합니다^^

추후에 (가능하다면? ㅠㅠ) 저도 사용하다가 공부해서 같이 기여할수있는것들이 있을수있도록 할께요.

**Comment by jeongukjae** [comment]
그렇게 생각해주시니 너무 감사해요! ㅋㅋㅋㅋ

사실 올해초 이후로 관리를 전혀 안하는 레포지토리였는데 다시 한번 들여다 보아야겠네요
